### ISSUE TITLE
Feature Request: Parameter to adjust the first day of the week

### ISSUE THREAD

**Issue by brossi** [RichDeBourke/scrollable-week-selector#1]
Thank you for making this plugin available, @RichDeBourke! I've been using it for simple HTML/jQuery interface prototypes and would like to discuss if you know of a straightforward way to patch in the ability to modify the default "first day of the week" from Sunday to another day.

**Use case**: 
Recently a lot of my UX design work is centered around products sold to the entertainment industry (movie studios, theaters, etc.) and to digital and TV advertisers.

  * My entertainment clients consider a "week" to run from Friday through Thursday
  * Some of my advertising clients prefer to define a weeks as "Sunday-Saturday" while others use the traditional broadcast week definition of "Monday-Sunday"

To sorta-kinda-not-really fake it in my designs I've taken to adjusting the order of the `dayNames` parameter on [Line 27](https://github.com/RichDeBourke/scrollable-week-selector/blob/master/js/jquery.calendar.js#L27), but it (logically) only changes the order and doesn't at all manipulate the actual calendar dates shown within each week. 

Having the ability to pass a parameter or to monkey-patch the `jquery.calendar.js` file individually as needed would make it far more convenient to use your plugin in my prototypes because I wouldn't need to explain before each demo why the viewer doesn't see what they expect to (e.g. "Friday, Jan. 27, 2019" vs. the correct "Friday, Jan. 25, 2019").

Thank you for the consideration and in advance for any support you have time to provide.

**Comment by RichDeBourke** [comment]
Hi @brossi – I can add a variable to the plugin’s settings for the starting day (1 through 7, with the default being 1 for Sunday). When a user clicks on a row, the calendar would provide the date for your selected start date (e.g. if the start day is Friday, then clicking on the row for Thursday, January 31, 2018 would call your function with the string “2019-01-25”).

I’ll make the change over the weekend and update the Feature Request thread when the plugin code is updated. I’ll update the README.md file next week.

Rich

**Comment by RichDeBourke** [comment]
Hi @brossi - I've added a option to set the start-day, with Sunday as 0 (I went with 0~6 as that's how the Date object works). The option is described in the README.md file.

To start the week on Thursday, add `startDay: 4,` to the plugin call. 

Rich

**Comment by brossi** [comment]
Thank you, @RichDeBourke! I'll pull the latest and give it a spin. Many thanks for the quick addition.
